# Generated by Django 5.2.4 on 2025-08-30 21:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PasswordReset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("otp", models.CharField(max_length=6)),
                ("token", models.CharField(max_length=255, unique=True)),
                ("otp_attempts", models.IntegerField(default=0)),
                ("email_attempts", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_otp_attempt", models.DateTimeField(blank=True, null=True)),
                ("last_email_sent", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField()),
                ("is_verified", models.BooleanField(default=False)),
                ("is_used", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="password_resets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "created_at"],
                        name="profiles_pa_user_id_9f8b42_idx",
                    ),
                    models.Index(
                        fields=["expires_at", "is_used"],
                        name="profiles_pa_expires_1f7996_idx",
                    ),
                    models.Index(fields=["token"], name="profiles_pa_token_9d1f1c_idx"),
                ],
            },
        ),
    ]
